//go:generate sh -c "cd ../static && npm run build"
//go:generate gostatic2lib -path ../static/dist/ -package webui -out static.go

package webui

import (
	"log"
	"net/http"
	"net/url"

	"github.com/qsoa-cloud/qdevrunner/instance"
	"github.com/qsoa-cloud/qdevrunner/logstore"
	mcppkg "github.com/qsoa-cloud/qdevrunner/mcp"
	"github.com/qsoa-cloud/qdevrunner/metricsstore"
	"github.com/qsoa-cloud/qdevrunner/tracer"
)

// Server is the Web UI HTTP server.
type Server struct {
	addr         string
	hub          *Hub
	instances    map[string]*instance.Instance
	tracerStore  *tracer.Store
	logStore     *logstore.Store
	metricsStore *metricsstore.Store
	cfg          *UIConfig
	mcpDeps      *mcppkg.Deps
}

// UIConfig contains configuration data to expose via the API.
type UIConfig struct {
	ProjectName string
	ProjectEnv  string
	Databases   map[string]mcppkg.DatabaseInfo
	Buckets     map[string]string
	Mailboxes   []string
}

func NewServer(addr string, instances map[string]*instance.Instance,
	ts *tracer.Store, ls *logstore.Store, ms *metricsstore.Store,
	cfg *UIConfig, mcpDeps *mcppkg.Deps) *Server {

	hub := NewHub(ts, ls, ms)

	return &Server{
		addr:         addr,
		hub:          hub,
		instances:    instances,
		tracerStore:  ts,
		logStore:     ls,
		metricsStore: ms,
		cfg:          cfg,
		mcpDeps:      mcpDeps,
	}
}

// Run starts the HTTP server. Blocks.
func (s *Server) Run() error {
	s.hub.Run()

	mux := http.NewServeMux()

	// MCP server at /mcp.
	mcpHandler := mcppkg.NewHandler(s.mcpDeps)
	mux.Handle("/mcp/", mcpHandler)
	mux.Handle("/mcp", mcpHandler)

	// WebSocket endpoint.
	mux.HandleFunc("/ws", s.hub.ServeWS)

	// API endpoints.
	mux.HandleFunc("/api/config", s.handleConfig)
	mux.HandleFunc("/api/services", s.handleServices)
	mux.HandleFunc("/api/services/", s.handleServiceAction)
	mux.HandleFunc("/api/config/", s.handleConfigManagement)
	mux.HandleFunc("/api/traces", s.handleTraces)
	mux.HandleFunc("/api/traces/", s.handleTrace)

	// Serve static files generated by gostatic2lib.
	staticHandler := NewHTTPHandler()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// SPA fallback: serve index.html for unknown paths.
		if file := staticHandler.GetFile(r.URL.Path); file == nil {
			r2 := new(http.Request)
			*r2 = *r
			r2.URL = new(url.URL)
			*r2.URL = *r.URL
			r2.URL.Path = "/"
			staticHandler.ServeHTTP(w, r2)
			return
		}
		staticHandler.ServeHTTP(w, r)
	})

	log.Printf("Web UI listening on http://%s", s.addr)
	log.Printf("MCP server at http://%s/mcp/", s.addr)
	return http.ListenAndServe(s.addr, mux)
}

// GetHub returns the WebSocket hub for external event broadcasting.
func (s *Server) GetHub() *Hub {
	return s.hub
}
