// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qmysql.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetDsnReq struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *GetDsnReq) Reset()         { *m = GetDsnReq{} }
func (m *GetDsnReq) String() string { return proto.CompactTextString(m) }
func (*GetDsnReq) ProtoMessage()    {}
func (*GetDsnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7d9e263a4a4dbb3, []int{0}
}
func (m *GetDsnReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetDsnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetDsnReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetDsnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDsnReq.Merge(m, src)
}
func (m *GetDsnReq) XXX_Size() int {
	return m.Size()
}
func (m *GetDsnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDsnReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDsnReq proto.InternalMessageInfo

func (m *GetDsnReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDsnResp struct {
	Dsn string `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
}

func (m *GetDsnResp) Reset()         { *m = GetDsnResp{} }
func (m *GetDsnResp) String() string { return proto.CompactTextString(m) }
func (*GetDsnResp) ProtoMessage()    {}
func (*GetDsnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7d9e263a4a4dbb3, []int{1}
}
func (m *GetDsnResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetDsnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetDsnResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetDsnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDsnResp.Merge(m, src)
}
func (m *GetDsnResp) XXX_Size() int {
	return m.Size()
}
func (m *GetDsnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDsnResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDsnResp proto.InternalMessageInfo

func (m *GetDsnResp) GetDsn() string {
	if m != nil {
		return m.Dsn
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDsnReq)(nil), "GetDsnReq")
	proto.RegisterType((*GetDsnResp)(nil), "GetDsnResp")
}

func init() { proto.RegisterFile("qmysql.proto", fileDescriptor_d7d9e263a4a4dbb3) }

var fileDescriptor_d7d9e263a4a4dbb3 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xcc, 0xad, 0x2c,
	0x2e, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe7, 0xe2, 0x74, 0x4f, 0x2d, 0x71,
	0x29, 0xce, 0x0b, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xe4, 0xb8, 0xb8, 0x60, 0x0a, 0x8a, 0x0b, 0x84, 0x04,
	0xb8, 0x98, 0x53, 0x8a, 0xf3, 0xa0, 0x0a, 0x40, 0x4c, 0x23, 0x2d, 0x2e, 0x56, 0xdf, 0xca, 0xe0,
	0xc2, 0x1c, 0x21, 0x45, 0x2e, 0x36, 0x88, 0x42, 0x21, 0x2e, 0x3d, 0xb8, 0x91, 0x52, 0xdc, 0x7a,
	0x08, 0xdd, 0x4e, 0x72, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c,
	0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xc5, 0xa2,
	0x67, 0x5d, 0x90, 0x94, 0xc4, 0x06, 0x76, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x75,
	0x20, 0x23, 0xa3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MySqlClient is the client API for MySql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MySqlClient interface {
	GetDsn(ctx context.Context, in *GetDsnReq, opts ...grpc.CallOption) (*GetDsnResp, error)
}

type mySqlClient struct {
	cc *grpc.ClientConn
}

func NewMySqlClient(cc *grpc.ClientConn) MySqlClient {
	return &mySqlClient{cc}
}

func (c *mySqlClient) GetDsn(ctx context.Context, in *GetDsnReq, opts ...grpc.CallOption) (*GetDsnResp, error) {
	out := new(GetDsnResp)
	err := c.cc.Invoke(ctx, "/MySql/GetDsn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySqlServer is the server API for MySql service.
type MySqlServer interface {
	GetDsn(context.Context, *GetDsnReq) (*GetDsnResp, error)
}

// UnimplementedMySqlServer can be embedded to have forward compatible implementations.
type UnimplementedMySqlServer struct {
}

func (*UnimplementedMySqlServer) GetDsn(ctx context.Context, req *GetDsnReq) (*GetDsnResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDsn not implemented")
}

func RegisterMySqlServer(s *grpc.Server, srv MySqlServer) {
	s.RegisterService(&_MySql_serviceDesc, srv)
}

func _MySql_GetDsn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDsnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySqlServer).GetDsn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MySql/GetDsn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySqlServer).GetDsn(ctx, req.(*GetDsnReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MySql_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MySql",
	HandlerType: (*MySqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDsn",
			Handler:    _MySql_GetDsn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qmysql.proto",
}

func (m *GetDsnReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetDsnReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetDsnReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQmysql(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetDsnResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetDsnResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetDsnResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dsn) > 0 {
		i -= len(m.Dsn)
		copy(dAtA[i:], m.Dsn)
		i = encodeVarintQmysql(dAtA, i, uint64(len(m.Dsn)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQmysql(dAtA []byte, offset int, v uint64) int {
	offset -= sovQmysql(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetDsnReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQmysql(uint64(l))
	}
	return n
}

func (m *GetDsnResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Dsn)
	if l > 0 {
		n += 1 + l + sovQmysql(uint64(l))
	}
	return n
}

func sovQmysql(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQmysql(x uint64) (n int) {
	return sovQmysql(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetDsnReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQmysql
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetDsnReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetDsnReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQmysql
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQmysql
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQmysql
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQmysql(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQmysql
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetDsnResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQmysql
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetDsnResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetDsnResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dsn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQmysql
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQmysql
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQmysql
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dsn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQmysql(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQmysql
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQmysql(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQmysql
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQmysql
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQmysql
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQmysql
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQmysql
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQmysql
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQmysql        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQmysql          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQmysql = fmt.Errorf("proto: unexpected end of group")
)
